-- Auto-generated by tools/scripts/determine-namemode.mjs
-- Generated: 2026-03-07T02:48:43.740Z

-- Disable audit triggers during bulk insert
ALTER TABLE "Mobs" DISABLE TRIGGER ALL;
ALTER TABLE "MobMaturities" DISABLE TRIGGER ALL;

-- Phase 1: NameMode corrections for existing maturities
UPDATE ONLY "MobMaturities" SET "NameMode" = 'Empty' WHERE "Id" IN (720, 1737, 968, 6841, 1738, 5038, 3588, 6157);

-- Phase 2: Add 27 maturities to existing mobs
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (399, '09', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (399, '08', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (399, '07', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (399, '06', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (399, '05', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (399, '04', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (399, '03', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (399, '02', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (399, '01', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (41, '06', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (41, '05', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (41, '08', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (41, '07', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (41, '04', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (41, '09', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (41, '03', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (41, '02', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (41, '01', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (39, '09', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (39, '08', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (39, '06', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (39, '05', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (39, '07', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (39, '04', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (39, '03', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (39, '02', 'Suffix') ON CONFLICT DO NOTHING;
INSERT INTO ONLY "MobMaturities" ("MobId", "Name", "NameMode") VALUES (39, '01', 'Suffix') ON CONFLICT DO NOTHING;

-- Re-enable audit triggers
ALTER TABLE "Mobs" ENABLE TRIGGER ALL;
ALTER TABLE "MobMaturities" ENABLE TRIGGER ALL;
